// Generated by Data/tools/build_promo.py — do not edit by hand.
import Foundation

/// One promo slide: an artwork that visibly contains `word`, with the
/// word's normalized bounding box for the highlight + lookup card.
struct PromoSlideData: Identifiable {
    let id: Int
    let imageName: String
    let word: String
    let x: Double
    let y: Double
    let width: Double
    let height: Double
}

enum PromoData {
    static let slides: [PromoSlideData] = [
    ]
}
